data_directory = "../Bahnhofottos/public/data/osm_data"
persistent_data = "../Bahnhofottos/public/data"
country_codes_file = "../Bahnhofottos/public/data/country_codes.json"
countries_interest_file = "../Bahnhofottos/public/data/countries_of_interest.json"
country_info = "../Bahnhofottos/public/data/country_info.json"
compiled_info = "../Bahnhofottos/public/data/compiled_country_info.json"
